Added batch inferencing
deven96/ahnlich pull request #134
Opened 2024-10-24 00:31 UTC by HAKSOAT

2024-10-24 15:42 UTC, deven96 commented on ahnlich/ai/src/engine/ai/providers/fastembed.rs
> +    fn run_inference(&self, inputs: &[ModelInput], action_type: &InputAction) -> Result<Vec<Vec<f32>>, AIProxyError> {
Can `run_inference` return the `Vec<StoreKey>`? so that higher up callers no longer have to iterate over the vec just to cast to another type

2024-10-24 15:46 UTC, deven96 requested changes
There shouldn't be any changes in the python lib I believe as protocol wasn't tampered with... so perhaps the changes that show up in Python are old? You can force checkout `sdk/ahnlich-client-py` from main to fix those

2024-10-24 15:46 UTC, deven96 commented on ahnlich/ai/src/engine/ai/models.rs
> +        let store_keys = embeddings
If we do [this](https://github.com/deven96/ahnlich/pull/134/files#r1815264646) we can get rid of this

2024-10-25 08:21 UTC, HAKSOAT commented
> There shouldn't be any changes in the python lib I believe as protocol wasn't tampered with... so perhaps the changes that show up in Python are old? You can force checkout `sdk/ahnlich-client-py` from main to fix those

The changes are cosmetic, it is because I ran typegen, but I will undo them.

2024-10-26 23:13 UTC, deven96 approved these changes

2024-10-26 23:14 UTC, merged