Implementing KDTree
deven96/ahnlich pull request #54
Opened 2024-06-30 21:55 UTC by deven96

2024-07-06 02:58 UTC, deven96 commented
I tried regenerating python client on this branch and got weird diffs @Iamdavidonuh . Did you change the target directory?

2024-07-06 07:08 UTC, Iamdavidonuh commented
> I tried regenerating python client on this branch and got weird diffs @Iamdavidonuh . Did you change the target directory?

@deven96  No I didn't, regenerating the Python client outputs in the right directory.
That being said, the files are to be manually moved to specific subdirs.
Probably that's where your diffs are coming from.

2024-07-09 10:16 UTC, Iamdavidonuh requested changes
Please format the python lib. `isort .` and then `black .`

2024-07-09 10:23 UTC, Iamdavidonuh approved these changes

2024-07-09 15:46 UTC, merged